spring:
  application:
    name: trsnc-test
  datasource:
    url: jdbc:mariadb://localhost:3306/tx
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB JDBC ???? ???
    hikari:
      pool-name: HikariCP         # ?? ??? ? (HikariCP)
      maximum-pool-size: 10       # ?? ??? ? ?? (??)
mybatis:
  mapper-locations: classpath:mapper/*.xml